/* Teilchenmodell ohne Atome/Moleküle (NaTech 7 / GB 6.10).
   Grössen, Farben und Verhalten sind didaktisch, nicht massstabsgetreu. */
window.SUBSTANCES = {
  water: {
    id: "water",
    name: "Wasser",
    short: "H₂O",
    color: "#3d9be9",
    stroke: "#1d6fad",
    r: 4.2,
    count: 36,
    density: 1,
    shape: "round",
    phase: "liquid",
    boil: 100,
    melt: 0,
    solubleIn: [],
    cluster: 1,
    magnetic: false,
    adsorbs: false,
    adsorbedBy: [],
    passesFilter: true,
    hint: "Lösungsmittel. Siedet bei 100 °C.",
  },
  alcohol: {
    id: "alcohol",
    name: "Alkohol",
    short: "Ethanol",
    color: "#5ecfb3",
    stroke: "#2a8f78",
    r: 4,
    count: 28,
    density: 0.79,
    shape: "round",
    phase: "liquid",
    boil: 78,
    melt: -114,
    solubleIn: [],
    cluster: 1,
    magnetic: false,
    adsorbs: false,
    adsorbedBy: [],
    passesFilter: true,
    extra: true,
    hint: "Mischt sich mit Wasser. Siedet schon bei 78 °C.",
  },
  salt: {
    id: "salt",
    name: "Salz",
    short: "Kochsalz",
    color: "#f4f6f8",
    stroke: "#9aa3ad",
    r: 5.2,
    count: 24,
    density: 2.16,
    shape: "crystal",
    phase: "solid",
    boil: 1465,
    melt: 801,
    solubleIn: ["water"],
    cluster: 6,
    magnetic: false,
    adsorbs: false,
    adsorbedBy: [],
    passesFilter: false,
    hint: "Kristall. Löst sich in Wasser, nicht in Alkohol.",
  },
  sugar: {
    id: "sugar",
    name: "Zucker",
    short: "Zucker",
    color: "#fff1c2",
    stroke: "#d2b56a",
    r: 4.4,
    count: 25,
    density: 1.59,
    shape: "round",
    phase: "solid",
    boil: 186,
    melt: 160,
    solubleIn: ["water"],
    cluster: 5,
    magnetic: false,
    adsorbs: false,
    adsorbedBy: [],
    passesFilter: false,
    hint: "Klümpchen aus etwa 5 Teilchen. Löst sich in Wasser.",
  },
  sand: {
    id: "sand",
    name: "Sand",
    short: "Sand",
    color: "#c9955a",
    stroke: "#8a5a28",
    r: 8.2,
    count: 16,
    density: 2.65,
    shape: "grain",
    phase: "solid",
    boil: 2230,
    melt: 1710,
    solubleIn: [],
    cluster: 1,
    magnetic: false,
    adsorbs: false,
    adsorbedBy: [],
    passesFilter: false,
    hint: "Unlöslich, schwer, bleibt im Filter.",
  },
  flour: {
    id: "flour",
    name: "Mehl",
    short: "Mehl",
    color: "#f3e6c8",
    stroke: "#cbb892",
    r: 5.6,
    count: 22,
    density: 1.15,
    shape: "flake",
    phase: "solid",
    boil: 400,
    melt: 400,
    solubleIn: [],
    cluster: 3,
    magnetic: false,
    adsorbs: false,
    adsorbedBy: [],
    passesFilter: false,
    hint: "Trübt Wasser, löst sich nicht, lässt sich filtrieren.",
  },
  charcoal: {
    id: "charcoal",
    name: "Aktivkohle",
    short: "Kohle",
    color: "#2b2d31",
    stroke: "#111213",
    r: 7.4,
    count: 12,
    density: 1.35,
    shape: "chunk",
    phase: "solid",
    boil: 4000,
    melt: 3500,
    solubleIn: [],
    cluster: 1,
    magnetic: false,
    adsorbs: true,
    adsorbedBy: [],
    passesFilter: false,
    hint: "Bindet Farbstoffe an der Oberfläche (Adsorbieren).",
  },
  iron: {
    id: "iron",
    name: "Eisenpulver",
    short: "Eisen",
    color: "#6d7380",
    stroke: "#3a3f48",
    r: 4.6,
    count: 20,
    density: 7.8,
    shape: "round",
    phase: "solid",
    boil: 2862,
    melt: 1538,
    solubleIn: [],
    cluster: 1,
    magnetic: true,
    adsorbs: false,
    adsorbedBy: [],
    passesFilter: false,
    hint: "Schwer und magnetisch — Alu nicht.",
  },
  alu: {
    id: "alu",
    name: "Aluminiumpulver",
    short: "Alu",
    color: "#c5ced6",
    stroke: "#7d8790",
    r: 4.6,
    count: 18,
    density: 2.7,
    shape: "round",
    phase: "solid",
    boil: 2470,
    melt: 660,
    solubleIn: [],
    cluster: 1,
    magnetic: false,
    adsorbs: false,
    adsorbedBy: [],
    passesFilter: false,
    hint: "Metallisch, aber nicht magnetisch.",
  },
  styrofoam: {
    id: "styrofoam",
    name: "Styropor",
    short: "Styropor",
    color: "#f7f7f4",
    stroke: "#c9c9c2",
    r: 11,
    count: 8,
    density: 0.04,
    shape: "foam",
    phase: "solid",
    boil: 240,
    melt: 240,
    solubleIn: [],
    cluster: 1,
    magnetic: false,
    adsorbs: false,
    adsorbedBy: [],
    passesFilter: false,
    hint: "Sehr leicht — schwimmt immer oben.",
  },
  wax: {
    id: "wax",
    name: "Wachs",
    short: "Wachs",
    color: "#f0d56a",
    stroke: "#c9a63a",
    r: 7.8,
    count: 10,
    density: 0.93,
    shape: "chunk",
    phase: "solid",
    boil: 300,
    melt: 62,
    solubleIn: [],
    cluster: 4,
    magnetic: false,
    adsorbs: false,
    adsorbedBy: [],
    passesFilter: false,
    hint: "Fest bei Raumtemperatur, schmilzt ab ca. 62 °C und schwimmt.",
  },
  ink: {
    id: "ink",
    name: "Tinte",
    short: "Tinte",
    color: "#5b2c91",
    stroke: "#3a1b62",
    r: 3.4,
    count: 22,
    density: 1.02,
    shape: "round",
    phase: "dissolved",
    boil: 100,
    melt: 0,
    solubleIn: ["water"],
    cluster: 1,
    magnetic: false,
    adsorbs: false,
    adsorbedBy: ["charcoal"],
    passesFilter: true,
    extra: true,
    hint: "Färbt Wasser. Aktivkohle kann sie adsorbieren, dann filtrieren.",
  },
};

window.TOOLS = [
  { id: "pointer", name: "Auswählen", icon: "👆" },
  { id: "stir", name: "Rühren", icon: "🥄" },
  { id: "heat", name: "Brenner", icon: "🔥" },
  { id: "thermo", name: "Thermometer", icon: "🌡️" },
  { id: "filter", name: "Filtrieren", icon: "▽" },
  { id: "distill", name: "Destillieren", icon: "⚗" },
  { id: "magnet", name: "Magnet", icon: "🧲" },
  { id: "decant", name: "Dekantieren", icon: "🫗" },
  { id: "empty", name: "Leeren", icon: "🗑️" },
];
